### PR TITLE
Some minor improvements

### PR DESCRIPTION
**Pull request by xiyuename**

### CODE REVIEW

**Comment by quantumbagel** [comment]
Hi Xiyue!

It seems like the fixes fall into three categories:

1. Caching more things (ion icons, font, etc.)
2. Removing comments / code cleanup
3. removing unused files from template


I honestly don't see anything gigantic here that I haven't already fixed yet. I will cache the font, but everything else is already there. I'll merge this if there's a genuine performance advantage other than the caching.

Thanks for the help!

**Comment by quantumbagel** [comment]
I've pushed my latest version. Check it out, and reopen if you have any more ideas :D

still have to add ion icon caching tho

**Comment by quantumbagel** [comment]
I've pushed my latest version. Check it out, and reopen if you have any more ideas :D

still have to add ion icon caching tho

**Comment by xiyuename** [comment]
Yes. After talking to you, I decided to stop working on it, so all you see is code generated by optimizers, not hand-written by me. The optimization only took me a few minutes.

I realized that there's a difference between what I do for my portfolio site and what you do for yours. I don't think it would make much sense for me to change your code since it's yours, not mine. And I don't have any suggestions since I don't know what your needs are for this site and its code.

I will focus on my own site, and when it reaches a stage where I feel satisfied to release it, I can share the code with you first. Personally, I feel that I put more effort into my site than you put into yours.

For the performance benefit part, I did implement some other things like font subsetting on my local end, but I didn't include them in this pull request.

**Comment by quantumbagel** [comment]
I agree that you probably did put more work in than me 👍

I'd love to see your website when it's ready!

**Pull request closed without merging**
